Updating some verisons in order to be compatible with Symfony 4.2
paysera/lib-serializer pull request #7
Opened 2019-05-20 13:14 UTC by victorlazov

2019-05-20 18:37 UTC, ghost reviewed
Let's allow PHP 7.1 as well. This is what SF 4 requires.

2019-05-20 18:41 UTC, ghost requested changes
Check inspections. I found "use Symfony\Component\Validator\ValidatorInterface" - undefined class. Might be other problems as well.

2019-05-21 05:27 UTC, tomas7777 commented
Why is the support for "3.*" being dropped? "3.*" is being actively used in many projects.

2019-05-21 06:38 UTC, theastar commented
> Why is the support for "3._" being dropped? "3._" is being actively used in many projects.

This library is rarely updated - has not been updated for about 7 months. If an update is needed for old versions of SF, maybe we can have a branch for them? Like for the old version 3.

2019-05-21 08:26 UTC, tomas7777 commented
It doesn't matter if it's rarely updated or not.
Making more branches doesn't make any sense in this case, because older symfony library support is backwards compatible (as it seems from your diff that no changes are needed), so there is no reason to drop support to them.

2019-05-21 13:58 UTC, victorlazov commented
Dependency versions lowered.
Major version bump in order 2.x and 3.x support to be distinguished clearly.

2019-05-21 16:45 UTC, vbartusevicius requested changes

2019-05-21 16:45 UTC, vbartusevicius commented on composer.json
> +        "symfony/validator": "^4.0",
please leave symfony 3.x support

2019-05-21 16:45 UTC, vbartusevicius commented on composer.json
> +        "php": "^7.1",
Please leave 7.0 support. I don't see where you use 7.1 features except `setUp` in tests. To have maximum backwards compatibility you should try to use lowest appropriate version.

2019-05-23 15:14 UTC, theastar commented on composer.json
> +        "symfony/validator": "^4.0",
Done

2019-05-23 15:15 UTC, ghost approved these changes

2019-05-23 15:43 UTC, vbartusevicius commented on .travis.yml
> -  - '7.0'
since your library is 7.0 compatible, please add 7.0 also

2019-05-23 15:43 UTC, vbartusevicius commented on CHANGELOG.md
> +"php": "^7.1",
this block needs to be synced with composer.json

2019-05-24 07:02 UTC, vbartusevicius approved these changes

2019-05-24 07:13 UTC, merged