Add support for PHP 8.0
paysera/lib-serializer pull request #8
Opened 2022-03-04 11:15 UTC by denjai

2022-03-04 11:28 UTC, edgar-zigis approved these changes

2022-03-04 15:23 UTC, zbpopova9292 approved these changes

2022-03-05 09:37 UTC, borilyordanov requested changes

2022-03-05 09:37 UTC, borilyordanov commented on composer.json
> +        "php": "^7.1 || ^8.0",
Is it necessary to drop the support for PHP 7.0? It is usually better for the library to be compatible with as many PHP versions as possible, unless this limits the development of the library.

2022-03-05 09:37 UTC, borilyordanov commented on CHANGELOG.md
> +## 4.0.0
Do we need to increment the major version? I don't see any changes in the public API of the library. Perhaps incrementing the minor version would be more appropriate. What do you think?

2022-03-08 09:09 UTC, borilyordanov approved these changes

2022-03-08 09:11 UTC, merged